services:
  - type: web
    name: farmassist-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
    branch: main
    region: oregon
    autoDeploy: true
    
